ExecuteInTx PostgreSQL version
heroiclabs/nakama pull request #1045
Opened 2023-07-03 19:10 UTC by redbaron

This PR attempts to improve ExecuteInTx in following ways:

- Previously it required call-site to provide `Tx`, but imposed restriction that caller must open, but don't use `Tx` prior to calling ExecuteInTx.  This change now enforces this contract by creating `Tx` internally, caller provides `*sql.DB` instead.

- ExecuteInTx was optimized for CockroachDB. Every transaction in addition to standard `BEGIN`/`COMMIT` had `SAVEPOINT` and `RELEASE SAVEPOINT` commands as the very first and very last commands in transaction. These are unnecessary in PG and add 2 additional round-trips to the database. For small and quick inserts additional round-trips are comparable to the query itself.  There is now separate version of `ExecuteInTx` for Cockroach and regular PosgreSQL. CockroachDB version is enabled at connection time based on result from `version()` SQL function.

- ExecuteInTx used to ignore `COMMIT` operation result. It wasn't a problem with CockroachDB, because commit actually happened on `RELEASE SAVEPOINT` and `COMMIT` couldn't fail. On PostgreSQL `COMMIT` can fail and ignoring possible errors is undesirable.

2023-07-10 19:39 UTC, ftkg requested changes

2023-07-10 21:07 UTC, redbaron commented on server/db.go
> +			err = tx.Commit()
Successfull commit  will exit on line 272

2023-07-11 05:46 UTC, redbaron commented on server/db.go
>  	for {
done

2023-07-11 12:53 UTC, ftkg approved these changes

2023-07-11 14:18 UTC, syhpoon approved these changes
:+1:

2023-07-11 14:39 UTC, zyro requested changes

2023-07-11 14:39 UTC, zyro commented on server/db.go
> +	if strings.Split(dbVersion, " ")[0] == "CockroachDB" {
I suggest we invert the logic slightly. Assume we should use the existing `ExecuteInTx` logic *unless* the version string does not contain `"CockroachDB"`. This way our default remain the current logic which is "safe", and we try to use the new logic conditionally on top.

2023-07-11 15:22 UTC, zyro commented on server/db.go
> +	if strings.Split(dbVersion, " ")[0] == "CockroachDB" {
Scratch that, it works out to the same thing.

2023-07-11 15:22 UTC, zyro approved these changes

2023-07-11 15:24 UTC, merged