Add config option to enforce a single session token per user
heroiclabs/nakama pull request #1175
Opened 2024-02-21 15:59 UTC by ftkg

Resolves #1014

2024-03-27 14:27 UTC, UmarBhatPlaystrom commented
+1

2024-03-27 15:07 UTC, waffillka commented
+1

2024-05-24 14:38 UTC, sesposito requested changes
@ftkg I believe that because `RemoveAll` invalidates all tokens emitted prior to the current time (with granularity within the same second), and because `IsValidSession` rejects tokens emitted within the same second too, this will also invalidate the token to be issued.

The new option should also be mentioned in the changelog.

2024-05-31 21:01 UTC, ftkg commented on server/session_cache.go
> +	if cache.lastInvalidation > 0 && exp-s.tokenExpirySec < cache.lastInvalidation {
@sesposito Good catch, I've changed the validity check to only deny tokens issued strictly before the full invalidation. Do you see any problems with this?

2024-06-03 18:33 UTC, sesposito approved these changes

2024-06-03 18:46 UTC, merged