feat: add delete confirmation dialog before real delete to prevent unexpected operation
heroiclabs/nakama pull request #1197
Opened 2024-04-10 14:01 UTC by xinatcg

<img width="536" alt="image" src="https://github.com/heroiclabs/nakama/assets/55399567/281375dc-8a33-4131-9329-9d107d77da31">

currently, all model messages are the same, but the service supports custom titles and content for different usage.

https://github.com/heroiclabs/nakama/issues/1123

2024-04-10 16:47 UTC, sesposito requested changes
Thank you very much for your contribution! 
The PR looks good, however, if possible, could you also replace the usage of the `confirmDelete` modal in config and chatMessages with the same approach?
Before this can be merged, you'll also need to run `npm run-script build`

2024-04-10 16:47 UTC, sesposito commented on console/ui/src/app/shared/delete-confirm.service.ts
> +      backdrop: false,
I suggest to add:
```
centered: true
```

2024-04-10 17:06 UTC, xinatcg commented on console/ui/src/app/shared/delete-confirm.service.ts
> +      backdrop: false,
ok, np thanks

2024-04-11 13:33 UTC, xinatcg commented
> The PR looks good, however, if possible, could you also replace the usage of the `confirmDelete` modal in config and chatMessages with the same approach?

Ok, if so
> The PR looks good, however, if possible, could you also replace the usage of the confirmDelete modal in config and chatMessages with the same approach?

Should we leave them out and only keep the code for others without confirmation?

2024-04-11 13:38 UTC, sesposito commented
I'll approve without those changes, but it would be good to touch on them as part of this PR, if possible. I think those modals aren't being displayed correctly due to the upgrade to Angular 15 merge.

2024-04-11 16:47 UTC, xinatcg commented
> I'll approve without those changes, but it would be good to touch on them as part of this PR, if possible. I think those modals aren't being displayed correctly due to the upgrade to Angular 15 changes.

make some updates to support formGroup with 2 control in the confirm component

2024-04-11 20:50 UTC, sesposito approved these changes
Left a couple of suggestions but otherwise LGTM 👍

2024-04-11 20:50 UTC, sesposito commented on console/ui/src/app/config/config.component.ts
> +      'Delete Project (NOT Configuration)' ,
```suggestion
      'Delete All Data' ,
```

2024-04-11 20:50 UTC, sesposito commented on console/ui/src/app/config/config.component.ts
> +      'Are you sure you want to delete all data?'
```suggestion
     'Are you sure you want to delete all the database data?'
```
This should make it clearer, what do you think?

2024-04-12 08:10 UTC, xinatcg commented
> Left a couple of suggestions but otherwise LGTM 👍

update with 2 suggestions. thanks

2024-04-12 16:18 UTC, sesposito commented
Please rerun `npm run build` and we'll get this merged 👍

2024-04-12 17:07 UTC, xinatcg commented
> npm run-script build

done

2024-04-12 17:07 UTC, xinatcg commented
> Please rerun `npm run build` and we'll get this merged 👍

done

2024-04-13 13:34 UTC, merged