Fix Go runtime shutdown function ctx
heroiclabs/nakama pull request #1231
Opened 2024-06-17 13:40 UTC by sesposito

2024-06-17 13:54 UTC, zyro requested changes

2024-06-17 13:58 UTC, syhpoon approved these changes

2024-06-17 14:22 UTC, sesposito commented
https://github.com/heroiclabs/nakama-common/pull/150

2024-06-18 10:17 UTC, zyro approved these changes

2024-06-18 10:22 UTC, merged