Nakama3 console api accounts list
heroiclabs/nakama pull request #505
Opened 2020-11-26 19:32 UTC by michal-harish

2020-11-26 21:09 UTC, mofirouz requested changes
Some changes required

2020-11-26 21:34 UTC, michal-harish commented on server/console_account.go
> +	users := make([]*api.User, 0, 2)
changing to use the const limit introduced above

2020-11-26 21:46 UTC, michal-harish commented on server/console_account.go
> +			addQueryCondition("username LIKE", in.Filter)
explain select id from users where username LIKE 'user%';
   tree    |    field    |       description        
-----------+-------------+--------------------------
           | distributed | false
           | vectorized  | false
 render    |             | 
  └── scan |             | 
           | table       | users@users_username_key
           | spans       | /"user"-/"uses"

2020-11-26 21:48 UTC, michal-harish commented on server/console_account.go
> +			addQueryCondition("username LIKE", in.Filter)
```
explain select id from users where username = 'user1';
   tree    |    field    |         description         
-----------+-------------+-----------------------------
           | distributed | false
           | vectorized  | false
 render    |             | 
  └── scan |             | 
           | table       | users@users_username_key
           | spans       | /"user1"-/"user1"/PrefixEnd
```

2020-11-26 21:49 UTC, michal-harish commented on console/console.proto
> +  string cursor = 4;
instead of `next_cursor` and `prev_cursor` there is only one cursor and a flag of direction `prev bool` which sets the direction of pivot

2020-11-27 08:26 UTC, mofirouz commented on server/console_account.go
> +			addQueryCondition("username LIKE", in.Filter)
And how would the LIKE% query look with a keyset where clause?

2020-11-27 10:36 UTC, michal-harish commented on server/console_account.go
> +			addQueryCondition("username LIKE", in.Filter)
i don't know, what sort of query do you have in mind conretely?

2020-11-27 10:37 UTC, michal-harish commented on console/console.proto
>    bool tombstones = 3;
yea could do, is that a 'go' or 'we should discuss this more' ?

2020-11-28 09:26 UTC, mofirouz commented on console/console.proto
>    bool tombstones = 3;
Let's leave it as it is for now.

2020-11-30 12:47 UTC, closed without merging