Add IAP Validation APIs
heroiclabs/nakama pull request #582
Opened 2021-03-31 15:59 UTC by sesposito

2021-04-01 18:51 UTC, zyro requested changes

2021-04-01 18:51 UTC, zyro commented on iap/iap.go
> +		return nil, []byte{}, errors.New("'url' must not be empty")
nit: Same throughout here, maybe better to use `nil` instead of `[]byte{}`.

2021-04-01 18:51 UTC, zyro commented on iap/iap.go
> +	token, err := GetGoogleAccessToken(ctx, httpc, clientEmail, privateKey)
Should a fresh access token be requested each time? If I recall last time I worked with similar Google services it should be possible to cache access tokens for some time.

2021-04-01 18:51 UTC, zyro commented on iap/iap.go
> +	data := &InAppPurchaseDataHuawei{PurchaseType: 2} // Set to placeholder value because field is omitted by prod purchase.
As discussed use a sentinel/placeholder value outside any possible valid range. Perhaps `-1` would be best?

2021-04-07 12:14 UTC, sesposito commented on console/console.swagger.json
> -  "tags": [
I've run `go generate -x` in the console as usual and this is removed, should I revert it?

2021-04-07 12:21 UTC, zyro commented on console/console.swagger.json
> -  "tags": [
It's interesting that each operation still contains a `"tags"` field, but the global one looks like it's been removed. I think if our codegens don't need the top-level tags then leave it removed.

2021-04-07 12:49 UTC, zyro requested changes

2021-04-07 12:49 UTC, zyro commented on iap/iap.go
> +		return cachedTokenGoogle.AccessToken, nil
Needs `cachedTokenGoogle.RUnlock()` before the return here.

2021-04-07 12:49 UTC, zyro commented on iap/iap.go
> +		return cachedTokenHuawei.AccessToken, nil
Needs `cachedTokenHuawei.RUnlock()` before the return here.

2021-04-07 12:49 UTC, zyro commented on server/core_purchase.go
> +	defer rows.Close()
There's already a `rows.Close()` after the loop so I would just move this into the loop ahead of the error return, rather than as a `defer` here.

2021-04-07 13:15 UTC, zyro approved these changes

2021-04-07 13:19 UTC, merged