Go func ref annotations
heroiclabs/nakama pull request #723
Opened 2021-11-29 08:39 UTC by gpene

@seanpackham for whoever we get to review this, the following need the more careful review/are missing definitions where I was unsure:
* MetricsCounterAdd
* MetricsGaugeSet
* MetricsTimerRecord
* SetEventFn
* ChannelIdBuild

2021-11-29 17:30 UTC, mofirouz requested changes
Absolutely fantastic work; Left some comments as you mentioned.

2021-11-29 17:30 UTC, mofirouz commented on server/runtime_go_nakama.go
> +// @summary Create a chat channel.
Helper function to create an channel identifier that can be used for various other runtime calls; Note, this does NOT create a channel.

Target: Can be the room name, group identifier, or another username

channelId: The generated ID that represents a channel.

2021-11-29 17:30 UTC, mofirouz commented on server/runtime_go_nakama.go
> +// @summary Send a message on a realtime chat channel.
SetEventFn - Register a function that processes events published to the server.

2021-11-29 17:30 UTC, mofirouz commented on server/runtime_go_nakama.go
> +// @param value(time.Duration)
Value - Value to update this metrics with.

2021-11-29 17:30 UTC, mofirouz commented on server/runtime_go_nakama.go
> +// @param value(float64)
Value - Value to update this metrics with.

2021-11-29 17:30 UTC, mofirouz commented on server/runtime_go_nakama.go
> +// @param delta(int64)
Delta - Value to update this metrics with.

2021-11-30 08:31 UTC, gpene commented
Thanks @mofirouz - updated with your comments.

2021-11-30 10:20 UTC, mofirouz approved these changes
Perfect, well done 👍

2021-12-13 12:42 UTC, zyro approved these changes

2021-12-13 12:42 UTC, merged