Expose leaderboardRecordsAroundOwner to JS runtime
heroiclabs/nakama pull request #766
Opened 2022-01-26 14:59 UTC by supernimbus-daithi

https://github.com/heroiclabs/nakama/issues/755

https://heroiclabs.com/docs/nakama/concepts/leaderboards/#list-leaderboard-records-around-owner

Fetches a list of leaderboard records around a owner. Please let me know if I should make any corrections.
The resulting LeaderboardRecordList[] reflects the same object returned by the Client API.

I will also create a PR for the nakama-common package to update the typing file.

2022-01-26 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/heroiclabs/nakama?pullRequest=766) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/heroiclabs/nakama?pullRequest=766) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/heroiclabs/nakama?pullRequest=766) it.</sub>

2022-01-26 15:47 UTC, sesposito requested changes
Thanks for your PR @supernimbus-daithi, much appreciated! 🙏
Left a couple of minor comments.
Please ensure you run `gofmt -w server/runtime_javascript_nakama.go` before you push the requested changes.

2022-01-26 15:47 UTC, sesposito commented on server/runtime_javascript_nakama.go
> +		if f.Argument(4) != goja.Undefined() {
I think this should be
```suggestion
		if f.Argument(3) != goja.Undefined() {
```

2022-01-26 15:47 UTC, sesposito commented on server/runtime_javascript_nakama.go
> +		"leaderboardRecordsAroundOwner":   n.leaderboardRecordsAroundOwner(r),
I think we should rename this to `tournamentRecordsHaystack` to keep it consistent with the lua runtime.
```suggestion
		"tournamentRecordsHaystack:   n.tournamentRecordsHaystack(r),
```

2022-01-26 15:53 UTC, supernimbus-daithi commented on server/runtime_javascript_nakama.go
> +		if f.Argument(4) != goja.Undefined() {
Good catch, updating now

2022-01-31 18:15 UTC, sesposito approved these changes

2022-01-31 18:16 UTC, merged