Add confirm dialog on delete actions
heroiclabs/nakama pull request #779
Opened 2022-02-08 08:54 UTC by Yanovskiy

Add confirm dialog modal on delete actions:
 - users
 - accounts
 - storage

2022-02-14 09:49 UTC, sesposito requested changes
Thank for your contribution @Yanovskiy, I think the addition of these confirmation dialogs can be a good idea, but instead of js dialogs it should be reworked to use the bootstrap modals for consistency. If you make these changes, please run the steps in the `console/ui` folder as well to package the console js code and include it into the PR.

2022-02-14 09:49 UTC, sesposito commented on console/ui/src/app/accounts/accounts.component.ts
> +    if (confirm('Are you sure to delete ' + o.username + '. All associated data will be lost')) {
The use of js confirm dialogs is discouraged as they cannot be styled and won't be consistent with the existing confirmation prompts we already have elsewhere (see: https://github.com/heroiclabs/nakama/blob/master/console/ui/src/app/config/config.component.html#L97).

2022-02-14 09:49 UTC, sesposito commented on console/ui/src/app/storage/storage.component.ts
> +    if (confirm('Are you sure to delete ' + o.key + ' from ' + o.collection + '?')) {
ditto

2022-02-14 09:49 UTC, sesposito commented on console/ui/src/app/users/users.component.ts
> +    if (confirm('Are you sure to delete ' + username)) {
ditto

2022-04-23 13:18 UTC, zyro commented
Closing as not mergeable in its current state. If the changes requested in the review can be made, we'd welcome a fresh PR! 👍

2022-04-23 13:18 UTC, closed without merging