Add condition healthcheck on Dockerfile
heroiclabs/nakama pull request #800
Opened 2022-03-03 16:11 UTC by tunglt1810

- Add version 3.8
- Add dependency condition with health check

2022-03-03 16:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/heroiclabs/nakama?pullRequest=800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/heroiclabs/nakama?pullRequest=800) before we can accept your contribution.<br/><hr/>**Jack Sparrow** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/heroiclabs/nakama?pullRequest=800) it.</sub>

2022-03-03 17:55 UTC, zyro commented
@tunglt1810 Could you please provide a bit more context on the rationale for this change?

2022-03-04 02:26 UTC, tunglt1810 commented
Hi @zyro,

I'm using Macbook pro 2021 with M1 Pro chip.

When i'm using Docker desktop with current docker-compose config with cockroachDB, the game server usually stop at the first time i start the container. Because of the game server try to connect DB when it's not ready. And to start game server, i need to manually start the game server again.

So with this change, docker will wait the db start and ready with healthcheck and start game server

2022-05-20 10:24 UTC, sesposito requested changes
Thank you @tunglt1810, this is a welcome addition, however I left a minor comment. Could you please also make the same changes to `docker-compose-postgres.yml` please?

2022-05-20 10:24 UTC, sesposito commented on docker-compose.yml
> +version: '3.8'
I suggest we keep this at `3` so we don't require the latest version as `condition` is supported anyway.

2022-05-24 10:10 UTC, closed without merging