Add iap refund support
heroiclabs/nakama pull request #959
Opened 2022-12-13 13:57 UTC by sesposito

Add IAP hooks for incoming Apple and Google notifications to handle refunds.

2022-12-15 09:46 UTC, zyro requested changes

2022-12-15 09:46 UTC, zyro commented on server/core_subscription.go
> +			if strings.ToUpper(notification.NotificationType) == "REFUND" {
Maybe use some constants, instead of `"REFUND"` as a string here?

2022-12-15 09:46 UTC, zyro commented on server/runtime.go
> +		return "subscription_notification_apple"
Typo, should be `_google`.

2022-12-15 09:46 UTC, zyro commented on server/runtime_lua.go
> +
Do we need the new execution modes added here?

2022-12-15 11:35 UTC, sesposito commented on iap/iap.go
> +/*type VoidedReceiptsGoogle struct {
Some code that once used but not anymore, will remove

2022-12-15 11:35 UTC, sesposito commented on iap/iap.go
> +			// goto
I was considering adding a retry mechanism but ended up scrapping it, will remove

2022-12-15 11:38 UTC, sesposito commented on server/core_purchase.go
> +		if purchase.refundTime == t {
Nice, didn't know about this

2022-12-16 14:39 UTC, zyro approved these changes

2022-12-16 15:37 UTC, merged